version: '3.9'

x-app-image: &app_image mini-bi-app:v1.0
x-app-environment: &app_environment
  API_PORT: 3000
  RUN_ETL_ON_BOOT: 'true'
  FAIL_ON_ETL_ERROR: 'true'
  DB_HOST: database
  DB_USER: root
  DB_PASSWORD: supersecret

services:
  database:
    image: mysql:8.0
    container_name: mini-bi-mysql
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -psupersecret']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  app-qa:
    image: *app_image
    build:
      context: .
      dockerfile: Dockerfile # Multi-stage: compila frontend y empaqueta backend en una sola imagen
    environment:
      <<: *app_environment
      APP_ENV: qa
      LOG_LEVEL: debug
      DB_NAME: dashboard_qa
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '3001:3000'

  app-prod:
    image: *app_image
    build:
      context: .
      dockerfile: Dockerfile # Multi-stage: compila frontend y empaqueta backend en una sola imagen
    environment:
      <<: *app_environment
      APP_ENV: prod
      LOG_LEVEL: warn
      DB_NAME: dashboard_prod
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '3002:3000'

volumes:
  mysql_data:
    driver: local
