# Usar una imagen base liviana y segura
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json primero para aprovechar el cache de Docker
COPY package*.json ./

# Instalar dependencias de producción
RUN npm install --production

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto
EXPOSE 3001

# Definir variable de entorno por defecto (puede ser sobrescrita por docker-compose)
ENV NODE_ENV=production

# Comando para iniciar la app
CMD ["node", "index.js"]